Update TF version in CI
Backblaze/terraform-provider-b2 pull request #12
Opened 2021-04-28 22:04 UTC by GoGstickGo

2021-04-29 16:30 UTC, mlech-reef requested changes

2021-04-29 16:30 UTC, mlech-reef commented on .github/workflows/ci.yml
>            - 0.15.0-beta2
Please remove

2021-04-29 19:26 UTC, GoGstickGo commented on .github/workflows/ci.yml
>            - 0.15.0-beta2
Roger that.

2021-04-29 19:56 UTC, ppolewicz commented
@mlech-reef CI is failing, but I don't understand why

2021-04-29 20:02 UTC, mlech-reef commented
> @mlech-reef CI is failing, but I don't understand why

The CI secrets are not inherited by the forks because of obvious security reasons. In SDK and CLI, the integration tests are skipped but not here.

2021-04-29 20:09 UTC, mlech-reef approved these changes

2021-04-29 20:41 UTC, mlech-reef commented
@GoGstickGo please rebase. I will test your changes manually.

2021-04-29 21:18 UTC, GoGstickGo commented
Roger that!

2021-05-05 19:56 UTC, GoGstickGo commented
Can u merge the  PR ? @mlech-reef

2021-05-06 22:13 UTC, ppolewicz commented
I see CI has failed, but I think it may have been caused by a bug that was fixed recently, so I re-ran it now, lets see if it works this time.

2021-05-07 23:41 UTC, ppolewicz commented
@mszumocki-reef please look into it - perhaps the fixed CI needs to be merged here (or rebased)?

2021-05-08 11:19 UTC, mlech-reef commented
@GoGstickGo @ppolewicz I have merged the `master` branch. Now everything should be fine. I will wait for CI to finish and merge.

2021-05-08 11:20 UTC, merged