Added static linux package building to support Alpine Linux
Backblaze/terraform-provider-b2 pull request #19
Opened 2021-06-27 20:51 UTC by wbancer-reef

Changes required to build static linux package, to support non-glibc distributions (mainly made for Apline Linux)

2021-06-29 08:18 UTC, mszumocki-reef approved these changes

2021-06-29 14:13 UTC, mlech-reef requested changes
Are you going to add CI to verify it is working on Alpine?

2021-06-29 14:21 UTC, mlech-reef commented
We have:
```
pyinstaller~=4.1
```

but I believe it won't work with `pyinstaler<4.3` as there was a problem with embedding files into executable when I tried to use `staticx` in the past. I see it was fixed in pyinstaller#5511.

Please bump the required version.

2021-07-06 09:19 UTC, merged

2021-07-06 09:29 UTC, mszumocki-reef commented
I've merged this to local alpine-support branch instead of master and fixed code review remarks.